### ISSUE TITLE
Add composer.json file

### ISSUE THREAD

**Issue by swissspidy** [aucor/rp4wp-polylang-compatibility#1]
This would be really helpful for adding this as a dependency.

**Comment by TeemuSuoranta** [comment]
Should this be added as a mu-plugin or regular plugin?

**Comment by swissspidy** [comment]
Regular plugin should be fine. Related Posts for WordPress is a regular plugin as well and there's no need for this one to be a mu-plugin.

**Comment by TeemuSuoranta** [comment]
That's true. There's checks for both Polylang and Related Posts for WordPress and annoying nags if they don't exist, but I guess mu-plugin is too much here. I'll try to add this soon. If you want it ASAP, I can take PR, too.

**Comment by TeemuSuoranta** [comment]
Kept you waiting, huh? I added the composer.json and submitted the plugin to the Packagist. You'll find the instructions on readme. I'll keep adding composer.jsons to the rest of our plugins.

**Comment by swissspidy** [comment]
No worries, thank you very much!
